<?php


namespace Tests\DocFlow\Unit\Domain;


use DocFlow\Domain\Clock;
use DocFlow\Domain\Clock\Fixed;
use DocFlow\Domain\Document;
use DocFlow\Domain\DocumentType;
use DocFlow\Domain\User;
use PHPUnit\Framework\TestCase;

class DocumentBaseTest extends TestCase
{
    /**
     * @var User
     */
    protected $author;
    /**
     * @var User
     */
    protected $verifier;

    protected function setUp(): void
    {
        $this->author = new User('author');
        $this->verifier = new User('verifier');
    }

    protected function createDocument(DocumentType $type): Document
    {
        $clock = $this->createClock();
        $number = $type . '/' . $clock->getDateTime()->format('Y/m/d');

        return new Document($type, $this->author, $clock); // ups, tu jest problem z czasem, zmienia sie
    }

    protected function createClock(): Clock
    {
        return new Fixed(new \DateTimeImmutable('2020-06-03 14:00:00'));
    }

    // ----------

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
    }

    public static function tearDownAfterClass(): void
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }
}