<?php

namespace Tests\DocFlow\Unit\Domain;

use DocFlow\Domain\Clock;
use DocFlow\Domain\Clock\Fixed;
use DocFlow\Domain\Document;
use DocFlow\Domain\DocumentStatus;
use DocFlow\Domain\DocumentType;
use DocFlow\Domain\User;
use PHPUnit\Framework\TestCase;

// TEST CASE CLASS PER CLASS
// TEST CASE CLASS PER FEATURE -> 2 podejscie
class DocumentCreationTest extends DocumentBaseTest
{
    /**
     * @test
     */
    public function testHasAutogeneratedNumber()
    {
        // Arrange / Given
        // Act / When
        $type = DocumentType::INSTRUCTION();
        $document = $this->createDocument($type);
        $number = $type . '/' . $this->createClock()->getDateTime()->format('Y/m/d');

        // Assert / Then
        $this->assertEquals(DocumentStatus::DRAFT(), $document->getStatus());
        $this->assertEquals($type, $document->getType());
        $this->assertEquals($this->author, $document->getAuthor());
        $this->assertEquals($number, $document->getNumber());
    }
}